- name: Add VirtualHost certificate file
  copy:
    src: "{{ item }}"
    dest: "/etc/pki/tls/certs/{{ item }}"
    owner: root
    group: root
    mode: '0777'
  with_items:
  - proxy_server.crt
  - www_server.crt
  - wordpress_server.crt
  notify:
  - Restart DNS
  
- name: Add VirtualHost ssl key
  copy:
    src: "{{ item }}"
    dest: "/etc/pki/tls/private/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
  - proxy_server.key
  - www_server.key
  - wordpress_server.key
  notify:
  - Restart DNS

- name: Add shared certificate
  copy:
    src: cacert.crt
    dest: /etc/pki/tls/certs/cacert.crt
    owner: root
    group: root
    mode: '0777'
  notify:
  - Restart DNS

- name: Add Dovecot certificate
  copy:
    src: "dovecot.crt"
    dest: "/etc/pki/dovecot/certs/dovecot.pem"
    owner: root
    group: root
    mode: '0777'
  notify:
  - Restart Dovecot

- name: Add Dovecot ssl key
  copy:
    src: "dovecot.key"
    dest: "/etc/pki/dovecot/private/dovecot.pem"
    owner: root
    group: root
    mode: '0777'
  notify:
  - Restart Dovecot