# 3.1 Understanding DNS CNAME records (added to template)

# 3.2 Virtual Web Hosts Using Apache Web Server
- name: Install httpd using dnf
  yum:
    name: httpd
    state: present

- name: permit traffic on port 80/tcp
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
  notify:
  - Restart firewall

- name: Ensure apache is running
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true

- name: Create directory /var/www/html/www.{{hostname}}/public_html
  file:
    path: /var/www/html/www.{{hostname}}/public_html
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create /etc/httpd/conf.d/www.{{hostname}}.conf
  template:
    src: www.b75914.conf.j2
    dest: /etc/httpd/conf.d/www.{{hostname}}.conf
    owner: root
    group: root
    mode: '0644'

- name: Create index.html for website
  template:
    src: index.html.j2
    dest: /var/www/html/www.{{hostname}}/public_html/index.html
    owner: root
    group: root
    mode: '0644'
  notify:
  - Restart Apache

# 3.3 Utilizing a web server as a proxy
- name: Add user proxy
  user:
    name: proxy
    
- name: Install python3-pip
  dnf:
    name: python3-pip

- name: Install flask
  pip:
    name: flask

- name: Create /etc/systemd/system/proxy.service
  copy:
    src: proxy.service
    dest: /etc/systemd/system/proxy.service
    owner: proxy
    group: root
    mode: '0755'
    
- name: Create proxy /usr/local/lib/server.py
  copy:
    src: server.py
    dest: /usr/local/lib/server.py
    owner: proxy
    group: root
    mode: '0755'

- name: Create /etc/httpd/conf.d/proxy.conf
  template:
    src: proxy.conf.j2
    dest: /etc/httpd/conf.d/proxy.conf
    owner: root
    group: root
    mode: '0644'

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: yes

- name: reload systemd
  command: systemctl daemon-reload

# MariaDB
- name: Install WordPress packages
  dnf:
    name:
    - php-mysqlnd
    - php-fpm
    - mariadb-server
    - httpd
    - tar
    - curl
    - php-json
    - mod_security

- name: Ensure MariaDB service is running
  systemd:
    name: mariadb
    state: started
    enabled: true

- name:  Security-hardening using mod_security
  copy:
    src: modsecurity_localrules.conf
    dest: /etc/httpd/modsecurity.d/local_rules/modsecurity_localrules.conf
    owner: root
    group: root
    mode: '0644'