- hosts: vm
  user: centos
  become: yes
  become_user: root
  vars:
  - hostname: b75914
  - domain_name: sa.cs.ut.ee
  - ip_address: 172.17.91.191
  - dns_zone: "{{hostname}}.sa.cs.ut.ee"
  - dns_serial_counter: 3

  # don't change
  - mysql_root_password: pass
  - dns_serial_counter_formatted: '{{ "%02d" | format(dns_serial_counter | int) }}'
  - dns_serial: "{{'%Y%m%d' | strftime(ansible_date_time.epoch) }}{{dns_serial_counter}}"
  
  pre_tasks:
  - name: Testing this out
    debug:
     msg: Hello


  roles:
  # - { role: etais, tags: etais } 
  # - { role: dns, tags: dns }
  # - { role: apache, tags: apache}
  # mysql_secure_installation
  # - { role: wordpress, tags: apache}
  # - { role: email, tags: email}
  - { role: roundcube, tags: email}