- hosts: vm
  user: centos
  become: yes
  become_user: root
  vars:
  - hostname: b75914
  - domain_name: sa.cs.ut.ee
  - ip_address: 172.17.89.26
  - dns_zone: "{{hostname}}.sa.cs.ut.ee"

  pre_tasks:
  - name: Testing this out
    debug: msg="Hello"

  # - name: Get OpenStack metadata
  #   uri:
  #     url: http://169.254.169.254/latest/meta-data/public-ipv4 
  #     method: GET
  #     status_code: 200
  #     return_content: yes
  #   register: cloud_metadata

  # - name: Create variable for IP address
  #   set_fact:
  #     ip_address: "{{ cloud_metadata.content }}"

  roles:
  # - { role: etais, tags: etais } 
  # - { role: dns, tags: dns }
  - { role: apache, tags: apache}