---
apiVersion: v1
kind: ConfigMap
metadata:
    name: laptop-config
    namespace: vols
data:
    laptop.brand: HP
    laptop.module: '840'
    laptop.gen: G8
---
apiVersion: v1
kind: Pod
metadata:
    name: laptop 
    namespace: vols
spec:
    containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: laptop-vol
        mountPath: /laptop
    volumes:
    - name: laptop-vol
      configMap:
        name: laptop-config