- name: Reminder
  debug: 
    msg: "Run mysql_secure_installation if this fails"

- name: Make sure pymysql is present
  pip:
    name: pymysql
    state: present
 
- name: Create /root/.my.cnf
  template:
    src: .my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0644'  

- name: Sets MySQL root password
  mysql_user: 
    name: root 
    password: "{{ mysql_root_password }}"  
    state: present

- name: Remove all anonymous user accounts
  mysql_user:
    name: ''
    host_all: true
    state: absent

- name: Remove MySQL test database
  mysql_db: 
    name: test
    state: absent

- name: Create database
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: Create user admin
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '{{ db_name }}.*:ALL,GRANT'
    state: present

# 4. Let's add a default WordPress setup to our current setup

- name: Extract wordpress.tar.gz
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/html
    remote_src: yes
    creates: /var/www/html/wordpress

- name: Update wordpress config
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
    owner: apache
    group: apache
    mode: '0666'

- name: Set ownership of wordpress directory to apache:apache
  file:
    path: /var/www/html/wordpress
    state: directory
    owner: apache
    group: apache
    recurse: yes

- name: Sefcontext | this equates to 'chcon -t httpd_sys_rw_content_t /var/www/html/wordpress -R'
  sefcontext:
    target: '/var/www/html/wordpress(/.*)?'
    setype: httpd_sys_rw_content_t
    state: present

- name: Create WordPress log files
  file:
    path: "{{ item }}"
    owner: apache
    group: apache
    mode: '0644'
    access_time: preserve
    modification_time: preserve 
    state: touch
  with_items:
  - /var/log/httpd/php-errors.log
  - /var/log/httpd/www-php-errors.log

- name: Update WordPress PHP log file locations
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: apache
    group: apache
    mode: '0666'
  with_items:
  - {dest: /etc/php-fpm.d/www.conf, src: www-error.log} # error_log = /var/log/httpd/www-php-errors.log
  - {dest: /etc/php-fpm.conf, src: error.log} # error_log = /var/log/httpd/php-errors.log

- name: Ensure MariaDB service is running
  ansible.builtin.service:
    name: php-fpm
    state: started
    enabled: true

- name: Create /etc/httpd/conf.d/wordpress.conf
  template:
    src: wordpress.conf.j2
    dest: /etc/httpd/conf.d/wordpress.conf
    owner: root
    group: root
    mode: '0644'

# 5. Configuring Apache modules
- name: Enable forensic logging
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    state: present
    regexp: "{{item}}"
    line: "{{item}}"
  with_items:
  - "LoadModule log_forensic_module modules/mod_log_forensic.so"

- name: Create forensic log file 
  file:
    path: "/var/log/httpd/{{item}}-forensic.log"
    owner: apache
    group: apache
    mode: '0644'
    access_time: preserve
    modification_time: preserve 
    state: touch
  with_items:
  - www.{{hostname}}
  - proxy

- name: Ensure apache is running
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true