- name: Restart Apache
  ansible.builtin.service:
    name: httpd 
    state: restarted

- name: Restart firewall
  systemd:
    name: firewalld
    state: restarted

- name: Restart DNS
  systemd:
    name: named
    state: restarted

- name: Restart Postfix
  systemd:
    name: postfix
    state: restarted


- name: Add user mailuser
  user:
    name: mailuser
    # password: pass