- name: Restart Apache
  service:
    name: httpd 
    state: restarted

- name: Restart firewall
  systemd:
    name: firewalld
    state: restarted

- name: Restart DNS
  systemd:
    name: named
    state: restarted

- name: Restart Postfix
  systemd:
    name: postfix
    state: restarted

- name: Restart Dovecot
  systemd:
    name: dovecot
    state: restarted

- name: Restart PHP
  systemd:
    name: php-fpm
    state: restarted

- name: Restart MariaDB
  systemd:
    name: mariadb
    state: restarted

- name: Restart rsyslog 
  systemd:
    name: rsyslog
    state: restarted