- name: Permit traffic on port
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  with_items:
  - 514
  - 30000
  - 30310
  - 30909
  - 30910
  notify:
  - Restart firewall

- name: Create 01-receiving.conf
  copy:
    src: 01-receiving.conf
    dest: /etc/rsyslog.d/01-receiving.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart rsyslog

- name: Edit rsyslog.conf
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart rsyslog

- name: Ensure rsyslog service is running
  systemd:
    name: rsyslog
    state: started
    enabled: true