---

# 3. Firewall - Open UDP and TCP port 53 for the lab
- name: Add DNS service rule
  ansible.posix.firewalld:
      service: dns
      permanent: true
      state: enabled

- name: permit traffic on port 8301/udp
  ansible.posix.firewalld:
    port: 8301/udp
    permanent: true
    state: enabled

- name: permit traffic on port 8301/tcp
  ansible.posix.firewalld:
    port: 8301/tcp
    permanent: true
    state: enabled

# 4. Disable IPv6
- name: DNS | Autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: yes

- name: Disable IPv6
  copy:
    src: 70-ipv6.conf
    dest: /etc/sysctl.d/70-ipv6.conf
    owner: root
    group: root
    mode: '0644'

- name: Change net.ipv6.conf.default.disable_ipv6 to 1.
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    sysctl_file: /etc/sysctl.d/70-ipv6.conf
    reload: yes

- name: Change net.ipv6.conf.all.disable_ipv6 to 1.
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    sysctl_file: /etc/sysctl.d/70-ipv6.conf
    reload: yes

# 5. Domain Name System (DNS) using BIND software
- name: Inserts into hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: '0644'

- name: Inserts into hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'

# 6. Configuring the BIND Name Server

- name: Install the latest version of bind
  ansible.builtin.yum:
    name: bind
    state: latest

- name: Install the latest version of bind-utils
  ansible.builtin.yum:
    name: bind-utils
    state: present

- name: Create directory for logging
  file:
    path: /var/named/log
    state: directory
    owner: named
    group: named
    mode: '0755'

- name: Create necessary files for logging
  file:
    path: /var/named/log/
    owner: named
    group: named
    mode: '0755'
    access_time: preserve
    modification_time: preserve 
    state: touch
  with_items:
  - default
  - auth_servers
  - zone_transfers
  - client_security
  - queries
  - query-errorsetc/named/b75914kUpdate /etc/

# Creating a Personal Domain for named

- name: Configure DNS server /etc/named.conf
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '0640'

- name: Create /etc/named directory
  file:
    path: /etc/named
    state: directory
    owner: named
    group: named
    mode: '0750'

- name: Update resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'

- name: Creating a Personal Domain for named {{dns_zone}}
  template:
    src: b75914.sa.cs.ut.ee.j2
    dest: /etc/named/{{hostname}}.{{domain_name}}
    owner: root
    group: named
    mode: '0644'
  notify:
  - Restart Apache

- name: Reverse DNS Domain for named {{reverse_dns}}
  template:
    src: (reversed_domain).in-addr.arpa.j2
    dest: /etc/named/{{reverse_dns}}
    owner: root
    group: named
    mode: '0644'
  notify:
  - Restart Apache

- name: Reload service firewalld
  systemd:
    name: firewalld
    state: restarted

- name: Start named service
  systemd:
    name: named
    state: started
    enabled: true