
# 3. Email in general

# 4. Postfix

- name: Install Postfix
  yum:
    name: postfix
    state: present

- name: Update Postfix main conf
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'

- name: Ensure Postfix service is running
  systemd:
    name: postfix
    state: started
    enabled: true

- name: Install passlib
  pip:
    name: passlib

- name: Add user mailuser
  user:
    name: mailuser
    password: "{{ mailuser_password | password_hash('sha512') }}"
    state: present

# Sending an e-mail task # TODO

# # 5. Dovecot

- name: Install Dovecot
  yum:
    name: dovecot
    state: present

- name: Ensure Dovecot service is running
  systemd:
    name: dovecot
    state: started
    enabled: true

- name: Configure Dovecot logging
  template:
    src: 10-logging.conf.j2
    dest: /etc/dovecot/conf.d/10-logging.conf
    owner: root
    group: root
    mode: '0644'
  notify:
  - Restart Dovecot

- name: Configure Dovecot authentication
  template:
    src: 10-auth.conf.j2
    dest: /etc/dovecot/conf.d/10-auth.conf
    owner: root
    group: root
    mode: '0644'
  notify:
  - Restart Dovecot

- name: Configure Dovecot mail
  template:
    src: 10-mail.conf.j2
    dest: /etc/dovecot/conf.d/10-mail.conf
    owner: root
    group: root
    mode: '0644'
  notify:
  - Restart Dovecot

- name: Configure Dovecot mail
  template:
    src: 10-mail.conf.j2
    dest: /etc/dovecot/dovecot.conf
    owner: root
    group: root
    mode: '0644'
  notify:
  - Restart Dovecot

- name: Add dovecot to mail group
  user:
    name: dovecot
    groups: mail
    append: true
    state: present

- name: Configure Dovecot mailbox
  template:
    src: 15-mailboxes.conf.j2
    dest: /etc/dovecot/conf.d/15-mailboxes.conf
    owner: root
    group: root
    mode: '0644'
  notify:
  - Restart Dovecot

# 5.2 Testing IMAP login

- name: Permit traffic on port
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  with_items:
  - 25
  - 143
  - 465
  - 993
  notify:
  - Restart firewall

- name: Install telnet
  yum:
    name: telnet
    state: present

# - name: Update Dovecot disable_plaintext_auth 
#   replace:
#     path: /etc/dovecot/conf.d/10-auth.conf
#     regexp: '#?disable_plaintext_auth\s*=.*[^#\n]' 
#     replace: disable_plaintext_auth = yes #disable_plaintext_auth = yes
#   notify:
#   - Restart Dovecot
    
# - name: Update Dovecot disable_plaintext_auth 
#   replace:
#     path: /etc/dovecot/conf.d/10-ssl.conf
#     regexp: '#?ssl\s*=.*[^#\n]' 
#     replace: ssl = no # ssl = required
#   notify:
#   - Restart Dovecot
    
# - name: Add lmtp protocol to Dovecot main conf
#   replace:
#     path: /etc/dovecot/dovecot.conf
#     regexp: '#?disable_plaintext_auth\s*=.*[^#\n]' 
#     replace: disable_plaintext_auth = yes #disable_plaintext_auth = yes
#   notify:
#   - Restart Dovecot

# # 5.3 Give mailbox handling from postfix to dovecot


# - name: Define lmtp listener
#   blockinfile:
#     path: /etc/dovecot/conf.d/10-master.conf
#     state: present
#     block: |
#       service lmtp {
#       unix_listener /var/spool/postfix/private/dovecot-lmtp { # unix_listener $PATH_TO_SOCKET
#         mode = 0600                                           # Socket permissions
#         user = postfix                                        # Socket owner
#         group = postfix                                       # Socket group
#         }
#       }

# - name: Update Dovecot mailbox_transport  
#   replace:
#     path: /etc/dovecot/conf.d/10-ssl.conf
#     regexp: '#?mailbox_transport \s*=.*[^#\n]' 
#     replace: mailbox_transport  = lmtp:unix:private/dovecot-lmtp # mailbox_transport = lmtp:unix:/var/lib/imap/socket/lmtp
#   notify:
#   - Restart Dovecot
#   - Restart Postfix

# # - name: Set postfix to also listen on submission port 
# #   blockinfile:
# #     path: /etc/postfix/master.cf
# #     state: present
# #     block: |
# #       submission inet n       -       n       -       -       smtpd
# #         -o syslog_name=postfix/submission
# #         -o smtpd_sasl_auth_enable=yes
# #         -o smtpd_recipient_restrictions=permit_mynetworks,permit_sasl_authenticated,reject
# #         -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
# #         -o smtpd_sasl_type=dovecot
# #         -o smtpd_sasl_path=private/auth

# #       # Explanations:
# #       #  -o syslog_name=postfix/submission: The name with which submission related events are logged
# #       #  -o smtpd_sasl_auth_enable=yes:     Enable sasl authentication (`plain` in our case)
# #       #  -o smtpd_recipient_restrictions=permit_mynetworks,permit_sasl_authenticated,reject: Permit recepients outside of $mynetworks only to authenticated users
# #       #  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject: Allow mail relaying only for authenticated users
# #       #  -o smtpd_sasl_type=dovecot:      Set dovecot as the SASL provider
# #       #  -o smtpd_sasl_path=private/auth: Set authentication socket location



# - name: Define auth service
#   blockinfile:
#     path: /etc/dovecot/conf.d/10-master.conf
#     state: present
#     block: |
#       service auth {
#         unix_listener /var/spool/postfix/private/auth {
#           mode = 0600
#           user = postfix
#           group = postfix
#         }
#       }













# # 6 Setting up a web service for mailbox access


# - name: Install dnf package
#   dnf:
#     autoremove: yes
#   with_items:
#   - epel-release
#   - dnf-plugins-core

# # dnf config-manager --set-enabled crb # TODO
# # - name: Enable CRB repository
# #   dnf:
# #     name: crb
# #     enablerepo: crb

# - name: Install yum package
#   yum:
#     name: "{{ item }}"
#     state: present
#   with_items:
#     - ImageMagick
#     - ImageMagick-devel
#     - ImageMagick-perl
#     - pcre-devel
#     - zlib
#     - zlib-devel
#     - libzip
#     #- libzip-devel # libzip-devel failed
#     - libmcrypt-devel
#     - php
#     - php-fpm
#     - php-devel
#     - php-pear
#     - php-cli
#     - php-gd
#     - php-curl
#     - php-xml
#     - php-mysqlnd
#     - php-mbstring
#     - php-intl
#     - php-ldap
#     - mariadb
#     - mariadb-server
#     - httpd
  
# - name: Install pecl package
#   community.general.pear:
#     name: pecl/json_post
#     state: present
#   with_items:
#   - imagick
#   - mcrypt 
#   - zip 

# - name: Create extensions file
#   file:
#     path: /etc/php.d/
#     dest: "20-{{ item }}.ini"
#     owner: root
#     group: root
#     mode: '0755'
#     access_time: preserve
#     modification_time: preserve 
#     state: touch
#     content: "extension={{ item }}"
#   with_items:
#   - imagick
#   - mcrypt 
#   - zip 