# 4. Postfix

- name: Yum install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - postfix
    - mod_ssl
    - cyrus-sasl-plain
    - telnet
    - dovecot

- name: Pip install passlib
  pip:
    name: passlib

- name: Configure Postfix
  template:
    src: "{{ item }}.j2"
    dest: "/etc/postfix/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
  - main.cf
  - master.cf
  notify:
  - Restart Postfix

- name: Ensure Postfix service is running
  systemd:
    name: postfix
    state: started
    enabled: true

- name: Add user mailuser
  user:
    name: mailuser
    password: "{{ mailuser_password | password_hash('sha512') }}"
    state: present

# Manually send e-mail for task

# 5. Dovecot

- name: Ensure Dovecot service is running
  systemd:
    name: dovecot
    state: started
    enabled: true

- name: Configure Dovecot
  template:
    src: "{{ item }}.j2"
    dest: "/etc/dovecot/conf.d/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
  - 10-logging.conf
  - 10-auth.conf
  - 10-mail.conf
  - 10-master.conf
  - 10-ssl.conf
  - 15-mailboxes.conf
  notify:
  - Restart Postfix

- name: Configure Dovecot
  template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf
    owner: root
    group: root
    mode: '0644'
  notify:
  - Restart Dovecot

- name: Add dovecot to mail group
  user:
    name: dovecot
    groups: mail
    append: true
    state: present

- name: Give mail group have write permissions to /var/mail
  file:
    path: /var/mail
    state: directory
    owner: root
    group: mail
    mode: '2777'

# 5.2 Testing IMAP login

- name: Permit traffic on port
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  with_items:
  - 25
  - 143
  - 465
  - 587
  - 993
  notify:
  - Restart firewall

# # 6 Setting up a web service for mailbox access

# run roundcube role